[package]
name = "nativecsvdiff"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.37.0", features = ["nif_version_2_15"] }
csv-diff = "0.1.1"
csv = "1.4.0"
